### ISSUE TITLE
Module crashing during packaging a build

### ISSUE THREAD

**Issue by orlandov** [ProjectBorealis/UE4GitPlugin#86] opened 2023-02-20 19:19 UTC
Hello there. I'm a long-time fan, and first-time bug submitter to this project. Recently, after upgrading to 5.1, I have been on the receiving end of 100% reproducible crashes in our packaging process:

```
LogShaderCompilers: Display: Shaders left to compile 0
LogModuleManager: Warning: GetModule racing against IsReady: GitSourceControl
LogWindows: Error: appError called: Assertion failed: Module [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp] [Line: 393]
GitSourceControl

LogThreadingWindows: Error: Runnable thread Background Worker #5 crashed.
LogWindows: Error: begin: stack for UAT
LogWindows: Error: === Critical error: ===
LogWindows: Error:
LogWindows: Error: Assertion failed: Module [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp
] [Line: 393]
LogWindows: Error: GitSourceControl
LogWindows: Error:
LogWindows: Error:
LogWindows: Error: [Callstack] 0x00007fff8a69cfd5 UnrealEditor-Core.dll!FModuleManager::LoadModuleChecked() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Modules\ModuleManager.cpp:393]
LogWindows: Error: [Callstack] 0x00007fff5c9af82b UnrealEditor-GitSourceControl.dll!GitSourceControlUtils::ParseFileStatusResult() [G:\IPX\MissionXR.Unreal\Plugins\GitSourceControl\Source\GitSourceControl\Private\GitSourceControlUtils.cpp:1085]
LogWindows: Error: [Callstack] 0x00007fff5c9b12ac UnrealEditor-GitSourceControl.dll!GitSourceControlUtils::ParseStatusResults() [G:\IPX\MissionXR.Unreal\Plugins\GitSourceControl\Source\GitSourceControl\Private\GitSourceControlUtils.cpp:1233]
LogWindows: Error: [Callstack] 0x00007fff5c9bcc3b UnrealEditor-GitSourceControl.dll!GitSourceControlUtils::RunUpdateStatus() [G:\IPX\MissionXR.Unreal\Plugins\GitSourceControl\Source\GitSourceControl\Private\GitSourceControlUtils.cpp:1465]
LogWindows: Error: [Callstack] 0x00007fff5c99e141 UnrealEditor-GitSourceControl.dll!FGitFetchWorker::Execute() [G:\IPX\MissionXR.Unreal\Plugins\GitSourceControl\Source\GitSourceControl\Private\GitSourceControlOperations.cpp:689]
LogWindows: Error: [Callstack] 0x00007fff5c999815 UnrealEditor-GitSourceControl.dll!FGitSourceControlCommand::DoThreadedWork() [G:\IPX\MissionXR.Unreal\Plugins\GitSourceControl\Source\GitSourceControl\Private\GitSourceControlCommand.cpp:46]
LogWindows: Error: [Callstack] 0x00007fff8a63e443 UnrealEditor-Core.dll!FQueuedThreadPoolWrapper::FScheduledWork::DoThreadedWork() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Misc\QueuedThreadPoolWrapper.h:128]
LogWindows: Error: [Callstack] 0x00007fff8a626d94 UnrealEditor-Core.dll!<lambda_2cfb882046ba83e24f4606b279dfb220>::operator()() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\Fundamental\Task.h:504]
LogWindows: Error: [Callstack] 0x00007fff8a634a33 UnrealEditor-Core.dll!LowLevelTasks::TTaskDelegate<LowLevelTasks::FTask * __cdecl(bool),48>::TTaskDelegateImpl<<lambda_2cfb882046ba83e24f4606b279dfb220>,0>::CallAndMove() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\Fundamental\TaskDelegate.h:171]
LogWindows: Error: [Callstack] 0x00007fff8a2bc39c UnrealEditor-Core.dll!LowLevelTasks::FTask::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\Fundamental\Task.h:656]
LogWindows: Error: [Callstack] 0x00007fff8a2bc286 UnrealEditor-Core.dll!LowLevelTasks::FScheduler::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:184]
LogWindows: Error: [Callstack] 0x00007fff8a29db88 UnrealEditor-Core.dll!LowLevelTasks::FScheduler::TryExecuteTaskFrom<&LowLevelTasks::TLocalQueueRegistry<1024>::TLocalQueue::DequeueGlobal,0>() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:361]
LogWindows: Error: [Callstack] 0x00007fff8a2df0f2 UnrealEditor-Core.dll!LowLevelTasks::FScheduler::WorkerMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\Fundamental\Scheduler.cpp:402]
LogWindows: Error: [Callstack] 0x00007fff8a2ac240 UnrealEditor-Core.dll!UE::Core::Private::Function::TFunctionRefCaller<<lambda_0a548c7e497de3cc77a9e48080e1524f>,void __cdecl(void)>::Call() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Templates\Function.h:475]
LogWindows: Error: [Callstack] 0x00007fff8a441d3b UnrealEditor-Core.dll!FThreadImpl::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\HAL\Thread.cpp:67]
LogWindows: Error: [Callstack] 0x00007fff8a9f5342 UnrealEditor-Core.dll!FRunnableThreadWin::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]
LogWindows: Error: [Callstack] 0x00007fff8a9ed230 UnrealEditor-Core.dll!FRunnableThreadWin::GuardedRun() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:79]
LogWindows: Error: [Callstack] 0x00007ff85ee27614 KERNEL32.DLL!UnknownFunction []
LogWindows: Error: [Callstack] 0x00007ff85ef826a1 ntdll.dll!UnknownFunction []
LogWindows: Error:
LogWindows: Error: Crash in runnable thread Background Worker #5
LogWindows: Error: end: stack for UAT
Took 134.70713279999998s to run UnrealEditor-Cmd.exe, ExitCode=3
ERROR: Cook failed.
       (see C:\Users\orlando\AppData\Roaming\Unreal Engine\AutomationTool\Logs\G+epic+UE_5.1\Log.txt for full exception trace)
AutomationTool executed for 0h 2m 22s
AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
```

After some futzing around trying different things, I found the following to have worked to alleviate the issue:

```
diff --git a/Plugins/GitSourceControl/GitSourceControl.uplugin b/Plugins/GitSourceControl/GitSourceControl.uplugin
index c77033b..93a830d 100644
--- a/Plugins/GitSourceControl/GitSourceControl.uplugin
+++ b/Plugins/GitSourceControl/GitSourceControl.uplugin
@@ -16,7 +16,7 @@
        "Modules": [
                {
                        "Name": "GitSourceControl",
-                       "Type": "UncookedOnly",
+                       "Type": "EditorNoCommandlet",
                        "LoadingPhase": "Default"
                }
        ]
```

**Comment by orlandov** [comment] 2023-02-20 21:26
I should mention the upstream is an Azure Devops instance, it has some interesting peculiarities in terms of how it does auth (I'm not an expert). This plugin usually works though.

**Comment by mastercoms** [comment] 2023-04-26 03:49
This is a duplicate of #80

**Closed as completed by mastercoms** 2023-04-26 03:49 UTC
